name: Build APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract Project
        run: unzip -o *.zip

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: gradle/actions/setup-gradle@v3

      - name: Compile APK
        run: |
          gradle wrapper --gradle-version 8.4
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon

      - uses: actions/upload-artifact@v4
        with:
          name: Multimedia-debug
          path: app/build/outputs/apk/debug/*.apk
